export const events = [
  {
    name: "Holiday Concert",
    day: "03",
    month: "Dec",
    date: new Date("2021-12-03"),
    ensemble: "Concert Band",
    location: "Valley Forge Military Academy",
    cityState: "Wayne, PA",
    time: "12:00PM",
  },
  {
    name: "Philadelphia Winter Parade",
    day: "04",
    month: "Dec",
    date: new Date("2021-12-03"),
    ensemble: "Ceremonial Band",
    location: "Philadelphia",
    cityState: "Philadelphia, PA",
    time: "12:00PM",
  },
  {
    name: "NJMEA",
    day: "24",
    month: "Jan",
    date: new Date("2021-12-03"),
    ensemble: "Jazz Band",
    location: "NJMEA",
    cityState: "New Jersey",
    time: "12:00PM",
  },
  {
    name: "NJMEA",
    day: "25",
    month: "Jan",
    date: new Date("2021-12-03"),
    ensemble: "Jazz Band",
    location: "NJMEA",
    cityState: "New Jersey",
    time: "12:00PM",
  },
  {
    name: "NJMEA",
    day: "26",
    month: "Jan",
    date: new Date("2021-12-03"),
    ensemble: "Jazz Band",
    location: "NJMEA",
    cityState: "New Jersey",
    time: "12:00PM",
  },
];
